### ISSUE TITLE
data and weight

### ISSUE THREAD

**Issue by world2025** [soumyadeep17/Improved_Contrast_Zero-DCE#1]
hello, would you like to share your data and weight?thx

**Comment by soumyadeep17** [comment]
Training Data : https://github.com/soumyadeep17/Improved_Contrast_Zero-DCE/tree/main/data/train_data
Test Data : https://github.com/soumyadeep17/Improved_Contrast_Zero-DCE/tree/main/data/test_data

**Comment by soumyadeep17** [comment]
for weights you can see the weights_init function defines in the program
weights are initialized as normal distrinutions

**Comment by world2025** [comment]
ok，thank you give me notice, do you do something about over_exposure enhancement? ahhh

**Comment by soumyadeep17** [comment]
Naah not till now .. 
You can check out this repository
https://github.com/mahmoudnafifi/Exposure_Correction

**Comment by world2025** [comment]
thx
